name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: apmserver.aldcejam.com
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd study
            git pull
            docker compose up --build -d
